- name: Generate and Distribute SSH Key
  hosts: all
  gather_facts: false
  vars:
    local_ssh_key_path: "~/.ssh/id_ed25519"
  tasks:
    - name: Check if SSH key exists on control node
      delegate_to: localhost
      stat:
        path: "{{ local_ssh_key_path }}.pub"
      register: ssh_key_check

    - name: Generate SSH key on control node if it does not exist
      delegate_to: localhost
      command: ssh-keygen -t ed25519 -f "{{ local_ssh_key_path }}" -N ""
      when: not ssh_key_check.stat.exists

    - name: Ensure .ssh directory exists on remote VMs
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy public key to authorized_keys on remote VMs
      become: true
      ansible.builtin.copy:
        src: "{{ local_ssh_key_path }}.pub"
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

