---
- name: Manage SSH Known Hosts and Authorized Keys for All VMs
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove old SSH host keys on control node
      shell: ssh-keygen -R {{ inventory_hostname }}
      delegate_to: localhost
      ignore_errors: yes
      register: remove_host_key_result

    - name: Add new SSH host keys on control node
      shell: ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      args:
        executable: /bin/bash
      delegate_to: localhost
      when: remove_host_key_result is not failed

    - name: Ensure .ssh directory exists on VMs
      ansible.builtin.file:
        path: /home/almalinux/.ssh
        state: directory
        mode: '0700'
        owner: almalinux
        group: almalinux

    - name: Copy public key to authorized_keys on VMs
      ansible.builtin.copy:
        src: /home/almalinux/ds4eng-infra/cnc-environment/lecturer_key.pub
        dest: /home/almalinux/.ssh/authorized_keys
        owner: almalinux
        group: almalinux
        mode: '0600'

