- name: Configure Redis to bind on 0.0.0.0 and allow external connections
  hosts: host
  become: yes
  tasks:
    - name: Ensure Redis is installed
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Ensure Python firewall library is installed
      ansible.builtin.yum:
        name: python3-firewall
        state: present

    - name: Ensure firewalld is installed and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configure Redis to bind on 0.0.0.0
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind .*'
        line: 'bind 0.0.0.0'
        backup: yes

    - name: Disable protected mode (optional)
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode .*'
        line: 'protected-mode no'
        backup: yes

    - name: Restart Redis to apply changes
      ansible.builtin.service:
        name: redis
        state: restarted
        enabled: yes

    - name: Ensure Redis port 6379 is open in the firewall
      ansible.builtin.firewalld:
        port: 6379/tcp
        permanent: yes
        state: enabled

    - name: Reload firewalld to apply rules
      ansible.builtin.command:
        cmd: firewall-cmd --reload

